version: "3.1"

services:
  db:
    container_name: db
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8000:8080"

volumes:
  mysql_data: